### ISSUE TITLE
请问一下要怎么使用？

### ISSUE THREAD

**Issue by ping1999** [Moran-Studio/AutoArknights#3]
比如说怎么 自己指定当前关卡 ？我勾选了“自己指定当前关卡”并运行会提示“自己指定关卡.正在检测是否开启代理”然后没有后文了。

**Comment by ping1999** [comment]
这是我选择LS5并运行之后
cmd里的信息
```
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "main.py", line 197, in LoopMission
TypeError: text(self, int): not enough arguments
```

**Comment by GitHub-moran** [comment]
请稍等，正在解决，预计明天就能正常运行了。
高考已完事，使用帮助正在编写。

**Comment by GitHub-moran** [comment]
> 比如说怎么 自己指定当前关卡 ？我勾选了“自己指定当前关卡”并运行会提示“自己指定关卡.正在检测是否开启代理”然后没有后文了。

自己指定关卡需要把界面调整到选关界面，然后勾选自己指定关卡，它就会自动检测代理，检测成功后开始自动运行。

**Comment by ping1999** [comment]
好的谢谢
